name: update-data

on: [push]
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-repository
      uses: actions/checkout@v4

    - name: python-setup
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: run-update-data
      run: python src/data_preprocessing/data_load.py

    - name: commit-push
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "chore: auto-update data"
        git push